name: Pull Docker Image and Scan Code

on:
  push:
    branches:
      - '**'  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - '**'  # Trigger the workflow on pull requests targeting the main branch
  workflow_dispatch:  

jobs:
  pull-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk Code Scan
        run: |
          snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Pull Docker Image
        run: |
          docker pull hello-world

      - name: Run Docker Image
        run: |
          docker run hello-world

      - name: List Docker Images
        run: |
          docker images
